#ifndef XEMU_PERF_TESTS_CPU_JUMP_CACHE_WORKLOAD_H
#define XEMU_PERF_TESTS_CPU_JUMP_CACHE_WORKLOAD_H

#include <cstdint>
#include <cstring>

namespace CpuJumpCache {
constexpr unsigned kPageBytes = 4096;
constexpr unsigned kMaximumTargets = 10;
constexpr uint32_t kOperations = 8000000;

inline unsigned Offset(unsigned index, bool collide) { return index * (collide ? 65 : 64); }

// Identifies xemu@76c23c7d's 4K-page/4096-slot softmmu hash, not a claim
// about a physical Xbox CPU cache. Host tests extract its bits independently.
inline unsigned Slot(uintptr_t pc) {
  const uintptr_t mixed = pc ^ (pc >> 6);
  return ((mixed >> 6) & 0xFC0) | (mixed & 0x3F);
}

inline bool Initialize(uint8_t* code, unsigned count, bool collide) {
  if (!code || (reinterpret_cast<uintptr_t>(code) & (kPageBytes - 1)) || !count || count > kMaximumTargets) {
    return false;
  }
  std::memset(code, 0x90, kPageBytes);
  for (unsigned index = 0; index < count; ++index) {
    // cdecl: mov eax,[esp+4]; xor eax,imm32; rol eax,7; add eax,imm32; ret
    const uint8_t instructions[] = {0x8B, 0x44, 0x24, 0x04, 0x35, 0, 0, 0, 0, 0xC1, 0xC0, 7, 0x05, 0, 0, 0, 0, 0xC3};
    uint8_t* target = code + Offset(index, collide);
    std::memcpy(target, instructions, sizeof(instructions));
    const uint32_t mask = (index + 1) * 0x9E3779B9U;
    const uint32_t addend = 0x7F4A7C15;
    std::memcpy(target + 5, &mask, sizeof(mask));
    std::memcpy(target + 13, &addend, sizeof(addend));
  }
  return true;
}

// Initialize and validate count before calling; generated bytes are immutable
// throughout every measured iteration. All targets stay within one guest page.
inline uint32_t Run(uint8_t* code, unsigned count, bool collide, uint32_t operations) {
  using Target = uint32_t (*)(uint32_t);
  Target volatile targets[kMaximumTargets];
  for (unsigned i = 0; i < count; ++i) {
    targets[i] = reinterpret_cast<Target>(code + Offset(i, collide));
  }
  uint32_t state = 0x12345678;
  for (uint32_t i = 0; i < operations; ++i) {
    state = targets[i % count](state ^ i);
  }
  return state;
}

inline uint32_t WorkChecksum(const uint8_t* code) {
  uint32_t hash = 2166136261U;
  for (unsigned i = 0; i < kPageBytes; ++i) {
    hash = (hash ^ code[i]) * 16777619U;
  }
  return hash;
}
}  // namespace CpuJumpCache
#endif  // XEMU_PERF_TESTS_CPU_JUMP_CACHE_WORKLOAD_H
