#!/usr/bin/env python3
"""Derive CPU-work oracles from semantics, never from measured guest output.

These four leaves validate arithmetic and immutable generated bytes. Rendering
is outside this oracle: no observed framebuffer or performance value is copied.
Historical references stay separate. Run with --output to create an immutable
reference for Xemu-Test-Runner's existing schema-1 functional-hash contract.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import struct


def recurrence(count: int) -> int:
    state = 0x12345678
    masks = [(i + 1) * 0x9E3779B9 & 0xFFFFFFFF for i in range(count)]
    for operation in range(8000000):
        value = state ^ operation ^ masks[operation % count]
        state = ((((value << 7) | (value >> 25)) & 0xFFFFFFFF) + 0x7F4A7C15) & 0xFFFFFFFF
    return state


def page_hash(count: int, stride: int) -> int:
    page = bytearray([0x90] * 4096)
    for index in range(count):
        # Encode the specified cdecl load/xor/rotate/add/return independently.
        code = (bytes.fromhex('8b44240435') +
                struct.pack('<I', (index + 1) * 0x9E3779B9 & 0xFFFFFFFF) +
                bytes.fromhex('c1c00705') + struct.pack('<I', 0x7F4A7C15) + b'\xc3')
        start = index * stride
        page[start:start + len(code)] = code
    value = 2166136261
    for byte in page:
        value = (value ^ byte) * 16777619 & 0xFFFFFFFF
    return value


def records() -> list[dict]:
    results = {count: recurrence(count) for count in (2, 8, 10)}
    rows = []
    for suffix, count, collide in (('collision2', 2, True), ('collision8', 8, True),
                                   ('collision10', 10, True), ('noncollision8', 8, False)):
        rows.append({
            'schema_version': 1, 'id': 'cpu_translation_blocks.jump_cache_' + suffix,
            'revision': 1, 'kind': 'leaf', 'outcome': 'PASS', 'iterations': 10,
            'sample_count': 10, 'measurement_iterations_multiplier': 1,
            'warmup_iterations': 0, 'gpu_completion_mode': 'per_iteration',
            'unit': 'us', 'direction': 'lower_is_better',
            'metadata': {'oracle_status': 'PASS', 'operations': 8000000,
                         'targets': count, 'colliding': collide,
                         'work_checksum': f'{page_hash(count, 65 if collide else 64):08x}',
                         'result_checksum': f'{results[count]:08x}'}
        })
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    data = records()
    # Never overwrite an existing pinned reference.
    with args.output.open('x', encoding='utf-8') as output:
        json.dump(data, output, indent=2)
        output.write('\n')


if __name__ == '__main__':
    main()
