#!/usr/bin/env python3
"""Generate deterministic, redistributable audio fixtures for the XISO.

The fixture payloads are synthetic test data. No third-party recordings are
used. Checked-in assets are intentionally small; large stress workloads are
generated by the guest at runtime.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import struct
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
AUDIO_ROOT = ROOT / "resources" / "audio"
MANIFEST_PATH = AUDIO_ROOT / "manifest.json"
CATALOG_PATH = ROOT / "src" / "generated" / "audio_fixture_catalog.inc"

STEP_TABLE = [
    7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31,
    34, 37, 41, 45, 50, 55, 60, 66, 73, 80, 88, 97, 107, 118, 130, 143,
    157, 173, 190, 209, 230, 253, 279, 307, 337, 371, 408, 449, 494, 544,
    598, 658, 724, 796, 876, 963, 1060, 1166, 1282, 1411, 1552, 1707,
    1878, 2066, 2272, 2499, 2749, 3024, 3327, 3660, 4026, 4428, 4871,
    5358, 5894, 6484, 7132, 7845, 8630, 9493, 10442, 11487, 12635,
    13899, 15289, 16818, 18500, 20350, 22385, 24623, 27086, 29794, 32767,
]
INDEX_TABLE = [-1, -1, -1, -1, 2, 4, 6, 8]


def fnv1a64(data: bytes) -> int:
    value = 14695981039346656037
    for byte in data:
        value ^= byte
        value = (value * 1099511628211) & 0xFFFFFFFFFFFFFFFF
    return value


def triangle_sample(phase: int) -> int:
    x = (phase >> 16) & 0xFFFF
    if x < 16384:
        value = x * 2
    elif x < 49152:
        value = 32767 - (x - 16384) * 2
    else:
        value = -32767 + (x - 49152) * 2
    return max(-32767, min(32767, value))


def triangle_frames(frame_count: int, sample_rate: int, frequencies: list[int]) -> list[int]:
    phases = [0] * len(frequencies)
    steps = [(frequency << 32) // sample_rate for frequency in frequencies]
    result: list[int] = []
    for _ in range(frame_count):
        for channel in range(len(frequencies)):
            result.append((triangle_sample(phases[channel]) * 3) // 4)
            phases[channel] = (phases[channel] + steps[channel]) & 0xFFFFFFFF
    return result


def wav_s16(samples: list[int], channels: int, sample_rate: int) -> bytes:
    payload = struct.pack("<" + "h" * len(samples), *samples)
    byte_rate = sample_rate * channels * 2
    block_align = channels * 2
    fmt = struct.pack("<HHIIHH", 1, channels, sample_rate, byte_rate, block_align, 16)
    return (
        b"RIFF"
        + struct.pack("<I", 4 + (8 + len(fmt)) + (8 + len(payload)))
        + b"WAVEfmt "
        + struct.pack("<I", len(fmt))
        + fmt
        + b"data"
        + struct.pack("<I", len(payload))
        + payload
    )


def lfsr32(value: int) -> int:
    if value == 0:
        value = 0x41554430
    lsb = value & 1
    value >>= 1
    if lsb:
        value ^= 0x80200003
    return value & 0xFFFFFFFF


def encode_nibble(target: int, predictor: int, index: int) -> tuple[int, int, int]:
    step = STEP_TABLE[index]
    difference = target - predictor
    sign = 8 if difference < 0 else 0
    difference = abs(difference)
    nibble = 0
    delta = step >> 3
    if difference >= step:
        nibble |= 4
        difference -= step
        delta += step
    if difference >= (step >> 1):
        nibble |= 2
        difference -= step >> 1
        delta += step >> 1
    if difference >= (step >> 2):
        nibble |= 1
        delta += step >> 2

    predictor += -delta if sign else delta
    predictor = max(-32768, min(32767, predictor))
    index = max(0, min(88, index + INDEX_TABLE[nibble]))
    return nibble | sign, predictor, index


def encode_adpcm_block(channels: list[list[int]]) -> bytes:
    if not channels or any(len(samples) != 65 for samples in channels):
        raise ValueError("ADPCM fixtures require exactly 65 samples per channel")

    predictors = [samples[0] for samples in channels]
    indices = [0] * len(channels)
    output = bytearray()
    for channel in range(len(channels)):
        output += struct.pack("<hBB", predictors[channel], indices[channel], 0)

    for chunk in range(8):
        for channel, samples in enumerate(channels):
            values = samples[1 + chunk * 8 : 1 + (chunk + 1) * 8]
            for offset in range(0, 8, 2):
                low, predictors[channel], indices[channel] = encode_nibble(
                    values[offset], predictors[channel], indices[channel]
                )
                high, predictors[channel], indices[channel] = encode_nibble(
                    values[offset + 1], predictors[channel], indices[channel]
                )
                output.append(low | (high << 4))
    return bytes(output)


def decode_adpcm_block(encoded: bytes, channel_count: int) -> list[int]:
    position = 0
    predictors: list[int] = []
    indices: list[int] = []
    channels = [[] for _ in range(channel_count)]

    for channel in range(channel_count):
        predictor, index, reserved = struct.unpack_from("<hBB", encoded, position)
        position += 4
        if not 0 <= index <= 88 or reserved != 0:
            raise ValueError("invalid generated ADPCM header")
        predictors.append(predictor)
        indices.append(index)
        channels[channel].append(predictor)

    chunks = (len(encoded) - 4 * channel_count) // (4 * channel_count)
    for _ in range(chunks):
        for channel in range(channel_count):
            for _ in range(4):
                packed = encoded[position]
                position += 1
                for nibble in (packed & 0xF, packed >> 4):
                    step = STEP_TABLE[indices[channel]]
                    delta = step >> 3
                    if nibble & 1:
                        delta += step >> 2
                    if nibble & 2:
                        delta += step >> 1
                    if nibble & 4:
                        delta += step
                    if nibble & 8:
                        delta = -delta
                    predictors[channel] = max(
                        -32768, min(32767, predictors[channel] + delta)
                    )
                    indices[channel] = max(
                        0, min(88, indices[channel] + INDEX_TABLE[nibble & 7])
                    )
                    channels[channel].append(predictors[channel])

    interleaved: list[int] = []
    for frame in range(len(channels[0])):
        for channel in range(channel_count):
            interleaved.append(channels[channel][frame])
    return interleaved


def build_fixtures() -> dict[str, bytes]:
    fixtures: dict[str, bytes] = {}

    fixtures["pcm_s16_stereo_48k_multitone.wav"] = wav_s16(
        triangle_frames(1024, 48000, [317, 541]), 2, 48000
    )

    impulse = [0] * 512
    for frame, amplitude in (
        (0, 30000), (1, -30000), (127, 20000), (256, -20000), (511, 12000)
    ):
        impulse[frame] = amplitude
    fixtures["pcm_s16_mono_44k1_impulse.wav"] = wav_s16(impulse, 1, 44100)

    noise: list[int] = []
    left, right = 0x41554430, 0x13579BDF
    for _ in range(512):
        left = lfsr32(left)
        right = lfsr32(right)
        left_sample = struct.unpack("<h", struct.pack("<H", (left >> 16) & 0xFFFF))[0] // 2
        right_sample = struct.unpack("<h", struct.pack("<H", (right >> 16) & 0xFFFF))[0] // 2
        noise.extend((left_sample, right_sample))
    fixtures["pcm_s16_stereo_48k_lfsr.wav"] = wav_s16(noise, 2, 48000)

    source = triangle_frames(256, 48000, [997])
    fixtures["raw/vp_s16_mono_48k_256.raw"] = struct.pack(
        "<" + "h" * len(source), *source
    )
    fixtures["raw/vp_s24_b32_mono_48k_256.raw"] = b"".join(
        struct.pack("<I", (sample << 8) & 0xFFFFFF) for sample in source
    )
    fixtures["raw/vp_s32_mono_48k_256.raw"] = b"".join(
        struct.pack("<i", sample << 16) for sample in source
    )

    mono = triangle_frames(65, 48000, [733])
    stereo = triangle_frames(65, 48000, [733, 1237])
    stereo_left = stereo[0::2]
    stereo_right = stereo[1::2]

    mono_adpcm = encode_adpcm_block([mono])
    stereo_adpcm = encode_adpcm_block([stereo_left, stereo_right])
    mono_decoded = decode_adpcm_block(mono_adpcm, 1)
    stereo_decoded = decode_adpcm_block(stereo_adpcm, 2)

    fixtures["raw/vp_adpcm_mono_block.raw"] = mono_adpcm
    fixtures["raw/vp_adpcm_mono_expected_s16.raw"] = struct.pack(
        "<" + "h" * len(mono_decoded), *mono_decoded
    )
    fixtures["raw/vp_adpcm_stereo_block.raw"] = stereo_adpcm
    fixtures["raw/vp_adpcm_stereo_expected_s16.raw"] = struct.pack(
        "<" + "h" * len(stereo_decoded), *stereo_decoded
    )
    return fixtures


FIXTURE_METADATA = [
    ("wav.multitone.s16.stereo.48k", "pcm_s16_stereo_48k_multitone.wav", "wav_pcm_s16", 2, 48000, 1024,
     "Audible left/right prime-frequency triangle tones for channel and AC97 sanity."),
    ("wav.impulse.s16.mono.44k1", "pcm_s16_mono_44k1_impulse.wav", "wav_pcm_s16", 1, 44100, 512,
     "Impulse train for resampler/boundary/dropout inspection."),
    ("wav.lfsr.s16.stereo.48k", "pcm_s16_stereo_48k_lfsr.wav", "wav_pcm_s16", 2, 48000, 512,
     "Deterministic wide-spectrum stereo noise for output-path corruption checks."),
    ("vp.s16.mono.48k.256", "raw/vp_s16_mono_48k_256.raw", "vp_pcm_s16", 1, 48000, 256,
     "Exact S16 VP source fixture."),
    ("vp.s24_b32.mono.48k.256", "raw/vp_s24_b32_mono_48k_256.raw", "vp_pcm_s24_b32", 1, 48000, 256,
     "Exact S24 samples packed in 32-bit containers for VP."),
    ("vp.s32.mono.48k.256", "raw/vp_s32_mono_48k_256.raw", "vp_pcm_s32", 1, 48000, 256,
     "Exact S32 VP source fixture."),
    ("vp.adpcm.mono.block", "raw/vp_adpcm_mono_block.raw", "vp_ima_adpcm", 1, 48000, 65,
     "One independent 36-byte Xbox/IMA ADPCM mono block."),
    ("vp.adpcm.mono.expected_s16", "raw/vp_adpcm_mono_expected_s16.raw", "golden_pcm_s16", 1, 48000, 65,
     "Decoded S16 golden for the mono ADPCM block."),
    ("vp.adpcm.stereo.block", "raw/vp_adpcm_stereo_block.raw", "vp_ima_adpcm", 2, 48000, 65,
     "One independent 72-byte Xbox/IMA ADPCM stereo block."),
    ("vp.adpcm.stereo.expected_s16", "raw/vp_adpcm_stereo_expected_s16.raw", "golden_pcm_s16", 2, 48000, 65,
     "Decoded interleaved S16 golden for the stereo ADPCM block."),
]


def build_manifest(fixtures: dict[str, bytes]) -> dict:
    records = []
    for fixture_id, path, encoding, channels, rate, frames, description in FIXTURE_METADATA:
        payload = fixtures[path]
        records.append({
            "id": fixture_id,
            "path": path,
            "disc_path": "D:\\audio\\" + path.replace("/", "\\"),
            "encoding": encoding,
            "channels": channels,
            "sample_rate_hz": rate,
            "frames": frames,
            "bytes": len(payload),
            "sha256": hashlib.sha256(payload).hexdigest(),
            "fnv1a64": f"{fnv1a64(payload):016x}",
            "description": description,
        })
    return {
        "schema_version": 1,
        "license": "Unlicense (repository LICENSE)",
        "source": "Procedurally generated by utils/generate_audio_fixtures.py; no third-party recordings.",
        "fixtures": records,
        "notes": {
            "midi": "Not included: MIDI/DirectMusic would test a sequencing/synthesis layer, not the MCPX VP/GP/EP hot paths targeted by this suite.",
            "adpcm": "The encoded blocks decode to 65 frames by IMA block semantics. The pinned xemu VP currently uses ADPCM_SAMPLES_PER_BLOCK=64 (with an in-source FIXME), so focused tests should treat the 65-frame golden as decoder truth and separately characterize VP consumption.",
            "u8": "U8 VP samples are generated deterministically at runtime from the integer S16 signal source. This avoids relying on a fragile checked-in high-byte raw payload while preserving exact repeatability.",
        },
    }


ENCODING_CPP = {
    "wav_pcm_s16": "kWavPcmS16",
    "vp_pcm_s16": "kVpPcmS16",
    "vp_pcm_s24_b32": "kVpPcmS24B32",
    "vp_pcm_s32": "kVpPcmS32",
    "vp_ima_adpcm": "kVpImaAdpcm",
    "golden_pcm_s16": "kGoldenPcmS16",
}


def render_cpp_catalog(manifest: dict) -> str:
    lines = [
        "// Generated by utils/generate_audio_fixtures.py. Do not edit by hand.",
        "static constexpr AudioFixtureSpec kAudioFixtureSpecs[] = {",
    ]
    for fixture in manifest["fixtures"]:
        path = fixture["disc_path"].replace("\\", "\\\\")
        lines.append(
            f'    {{"{fixture["id"]}", "{path}", '
            f'AudioFixtureEncoding::{ENCODING_CPP[fixture["encoding"]]}, '
            f'{fixture["channels"]}U, {fixture["sample_rate_hz"]}U, '
            f'{fixture["frames"]}U, {fixture["bytes"]}U, '
            f'0x{fixture["fnv1a64"]}ULL}},'
        )
    lines.extend([
        "};",
        "static constexpr size_t kAudioFixtureSpecCount =",
        "    sizeof(kAudioFixtureSpecs) / sizeof(kAudioFixtureSpecs[0]);",
        "",
    ])
    return "\n".join(lines)


def generated_outputs() -> tuple[dict[str, bytes], str, str]:
    fixtures = build_fixtures()
    manifest = build_manifest(fixtures)
    manifest_text = json.dumps(manifest, indent=2) + "\n"
    catalog_text = render_cpp_catalog(manifest)
    return fixtures, manifest_text, catalog_text


def check() -> int:
    fixtures, manifest_text, catalog_text = generated_outputs()
    mismatches = []
    for relative_path, expected in fixtures.items():
        path = AUDIO_ROOT / relative_path
        if not path.exists() or path.read_bytes() != expected:
            mismatches.append(str(path.relative_to(ROOT)))
    if not MANIFEST_PATH.exists() or MANIFEST_PATH.read_text(encoding="utf-8") != manifest_text:
        mismatches.append(str(MANIFEST_PATH.relative_to(ROOT)))
    if not CATALOG_PATH.exists() or CATALOG_PATH.read_text(encoding="utf-8") != catalog_text:
        mismatches.append(str(CATALOG_PATH.relative_to(ROOT)))

    if mismatches:
        print("audio fixture generation is stale:")
        for path in mismatches:
            print(f"  {path}")
        return 1
    print(f"audio fixtures current: {len(fixtures)} files")
    return 0


def write() -> None:
    fixtures, manifest_text, catalog_text = generated_outputs()
    for relative_path, payload in fixtures.items():
        path = AUDIO_ROOT / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)
    MANIFEST_PATH.write_text(manifest_text, encoding="utf-8")
    CATALOG_PATH.write_text(catalog_text, encoding="utf-8")
    print(f"wrote {len(fixtures)} audio fixtures")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        return check()
    write()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
